[package]
name = "deno_brotli"
version = "0.1.0"
authors = ["Elias SJögreen", "Divy Srivastava"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
brotli = "3.3.0"
wee_alloc = "0.4.5"

[profile.release]
lto = true
